CREATE TABLE IF NOT EXISTS community_groups(
 id BIGSERIAL PRIMARY KEY,chat_id BIGINT NOT NULL UNIQUE REFERENCES chats(id) ON DELETE CASCADE,
 kind VARCHAR(32) NOT NULL,key_name VARCHAR(255) NOT NULL UNIQUE,title VARCHAR(255) NOT NULL,hidden_default BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS location_communities(
 location_key VARCHAR(255) PRIMARY KEY,location_title VARCHAR(255) NOT NULL,chat_id BIGINT UNIQUE REFERENCES chats(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS privacy_settings(
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 location_group_visible BOOLEAN NOT NULL DEFAULT FALSE,school_group_visible BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS user_consents(
 user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,consent_type VARCHAR(64) NOT NULL,granted BOOLEAN NOT NULL,version VARCHAR(32) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,consent_type)
);
