CREATE TABLE IF NOT EXISTS calls(id VARCHAR(32) PRIMARY KEY,creator_id BIGINT NOT NULL,kind VARCHAR(8) NOT NULL CHECK(kind IN ('audio','video')),status VARCHAR(16) NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ended_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS participants(call_id VARCHAR(32) REFERENCES calls(id) ON DELETE CASCADE,user_id BIGINT NOT NULL,role VARCHAR(16) NOT NULL,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),left_at TIMESTAMPTZ,PRIMARY KEY(call_id,user_id));
CREATE INDEX IF NOT EXISTS idx_calls_expiry ON calls(expires_at,status);
