<?php
declare(strict_types=1);
namespace PlusChat;
use PlusChat\Auth\Auth;
use PlusChat\Http\Request;
use PlusChat\Http\Response;
final class ApiController{
 private function u(Request $r):array{return Auth::require($r);}
 private function member(int $chat,int $user):?string{$s=Database::pdo()->prepare('SELECT role FROM chat_members WHERE chat_id=? AND user_id=?');$s->execute([$chat,$user]);$v=$s->fetchColumn();return $v===false?null:(string)$v;}
 public function me(Request $r):Response{$u=$this->u($r);unset($u['password_hash']);return Response::json(['user'=>$u]);}
 public function logout(Request $r):Response{$u=$this->u($r);Database::pdo()->prepare('UPDATE sessions SET revoked_at=NOW() WHERE id=?')->execute([$u['session_id']]);return Response::json(['ok'=>true]);}
 public function logoutAll(Request $r):Response{$u=$this->u($r);Database::pdo()->prepare('UPDATE sessions SET revoked_at=NOW() WHERE user_id=?')->execute([$u['id']]);return Response::json(['ok'=>true]);}
 public function users(Request $r):Response{$u=$this->u($r);$q=trim((string)($r->query['q']??$r->json()['q']??''));if(mb_strlen($q)<2)return Response::json(['users'=>[]]);$s=Database::pdo()->prepare("SELECT id,username,display_name,avatar_file_id,bio FROM users WHERE is_blocked=FALSE AND id<>? AND (username ILIKE ? OR display_name ILIKE ?) ORDER BY username NULLS LAST LIMIT 30");$s->execute([$u['id'],'%'.$q.'%','%'.$q.'%']);return Response::json(['users'=>$s->fetchAll()]);}
 public function chats(Request $r):Response{$u=$this->u($r);$s=Database::pdo()->prepare("SELECT c.*,cm.role FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=? ORDER BY c.updated_at DESC,c.id DESC");$s->execute([$u['id']]);return Response::json(['chats'=>$s->fetchAll()]);}
 public function chatCreate(Request $r):Response{$u=$this->u($r);$b=$r->json();$type=(string)($b['type']??'private');if(!in_array($type,['private','group','channel'],true))return Response::json(['error'=>['code'=>'INVALID_TYPE']],422);$p=Database::pdo();$p->beginTransaction();try{$s=$p->prepare('INSERT INTO chats(type,title,description,created_by) VALUES(?,?,?,?) RETURNING id');$s->execute([$type,$b['title']??null,$b['description']??null,$u['id']]);$id=(int)$s->fetchColumn();$p->prepare('INSERT INTO chat_members(chat_id,user_id,role) VALUES(?,?,?)')->execute([$id,$u['id'],'owner']);if($type==='group')$p->prepare('INSERT INTO groups(chat_id,topics_enabled) VALUES(?,?)')->execute([$id,(bool)($b['topics_enabled']??false)]);if($type==='channel')$p->prepare('INSERT INTO channels(chat_id,is_public,username) VALUES(?,?,?)')->execute([$id,(bool)($b['public']??false),$b['username']??null]);$p->commit();return Response::json(['chat_id'=>$id],201);}catch(\Throwable $e){$p->rollBack();throw $e;}}
 public function membersAdd(Request $r):Response{$u=$this->u($r);$b=$r->json();$chat=(int)($b['chat_id']??0);$target=(int)($b['user_id']??0);$role=$this->member($chat,$u['id']);if(!in_array($role,['owner','admin','moderator'],true))return Response::json(['error'=>['code'=>'FORBIDDEN']],403);Database::pdo()->prepare('INSERT INTO chat_members(chat_id,user_id,role) VALUES(?,?,?) ON CONFLICT DO NOTHING')->execute([$chat,$target,'member']);return Response::json(['ok'=>true]);}
 public function messages(Request $r):Response{$u=$this->u($r);$chat=(int)($r->query['chat_id']??$r->json()['chat_id']??0);if(!$this->member($chat,$u['id']))return Response::json(['error'=>['code'=>'FORBIDDEN']],403);$limit=min(100,max(1,(int)($r->query['limit']??50)));$s=Database::pdo()->prepare("SELECT m.id,m.chat_id,m.sender_id,m.body,m.reply_to_id,m.topic_id,m.edited_at,m.deleted_at,m.created_at,u.username,u.display_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.chat_id=? ORDER BY m.id DESC LIMIT {$limit}");$s->execute([$chat]);return Response::json(['messages'=>array_reverse($s->fetchAll())]);}
 public function messageSend(Request $r):Response{$u=$this->u($r);$b=$r->json();$chat=(int)($b['chat_id']??0);$body=trim((string)($b['body']??''));if($body===''||mb_strlen($body)>20000)return Response::json(['error'=>['code'=>'INVALID_BODY']],422);if(!$this->member($chat,$u['id']))return Response::json(['error'=>['code'=>'FORBIDDEN']],403);$p=Database::pdo();$s=$p->prepare('INSERT INTO messages(chat_id,sender_id,body,reply_to_id,topic_id) VALUES(?,?,?,?,?) RETURNING id,created_at');$s->execute([$chat,$u['id'],$body,$b['reply_to_id']??null,$b['topic_id']??null]);$row=$s->fetch();$p->prepare('UPDATE chats SET updated_at=NOW() WHERE id=?')->execute([$chat]);return Response::json(['message'=>$row],201);}
 public function messageEdit(Request $r):Response{$u=$this->u($r);$b=$r->json();$body=trim((string)($b['body']??''));if($body===''||mb_strlen($body)>20000)return Response::json(['error'=>['code'=>'INVALID_BODY']],422);$s=Database::pdo()->prepare('UPDATE messages SET body=?,edited_at=NOW() WHERE id=? AND sender_id=? AND deleted_at IS NULL');$s->execute([$body,(int)$b['message_id'],$u['id']]);return Response::json(['ok'=>$s->rowCount()===1]);}
 public function messageDelete(Request $r):Response{$u=$this->u($r);$s=Database::pdo()->prepare('UPDATE messages SET deleted_at=NOW(),body=NULL WHERE id=? AND sender_id=? AND deleted_at IS NULL');$s->execute([(int)$r->json()['message_id'],$u['id']]);return Response::json(['ok'=>$s->rowCount()===1]);}
 public function reaction(Request $r):Response{$u=$this->u($r);$b=$r->json();$p=Database::pdo();$p->prepare('INSERT INTO message_reactions(message_id,user_id,emoji) VALUES(?,?,?) ON CONFLICT(message_id,user_id,emoji) DO NOTHING')->execute([(int)$b['message_id'],$u['id'],(string)$b['emoji']]);return Response::json(['ok'=>true]);}
 public function settings(Request $r):Response{$u=$this->u($r);$p=Database::pdo();if($r->method==='GET'){$s=$p->prepare('SELECT settings FROM user_settings WHERE user_id=?');$s->execute([$u['id']]);return Response::json(['settings'=>$s->fetchColumn()?:new \stdClass]);}$settings=$r->json()['settings']??[];$p->prepare('INSERT INTO user_settings(user_id,settings) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET settings=EXCLUDED.settings')->execute([$u['id'],json_encode($settings,JSON_UNESCAPED_UNICODE)]);return Response::json(['ok'=>true]);}
}
