<?php
declare(strict_types=1);
namespace PlusChat;
use PlusChatHttpRequest; use PlusChatHttpResponse; use PlusChatAuthAuth; use PlusChatSecuritySecurity;
final class ApiController {
 private function user(Request $r): array { $u=Auth::user($r); if(!$u) throw new \RuntimeException('unauthorized'); return $u; }
 private function ok(mixed $d=[],int $s=200): Response{return Response::json($d,$s);}
 public function me(Request $r):Response{$u=$this->user($r); return $this->ok(['user'=>$u]);}
 public function logout(Request $r):Response{$u=$this->user($r); Database::pdo()->prepare('UPDATE sessions SET revoked_at=NOW() WHERE id=:id')->execute(['id'=>$u['session_id']]);return $this->ok(['ok'=>true]);}
 public function logoutAll(Request $r):Response{$u=$this->user($r);Database::pdo()->prepare('UPDATE sessions SET revoked_at=NOW() WHERE user_id=:u')->execute(['u'=>$u['id']]);return $this->ok(['ok'=>true]);}
 public function users(Request $r):Response{$u=$this->user($r);$q=trim((string)($r->json()['q']??''));if(strlen($q)<2)return $this->ok(['users'=>[]]);$st=Database::pdo()->prepare("SELECT id,username,display_name,avatar_file_id,bio FROM users WHERE is_blocked=FALSE AND (username ILIKE :q OR display_name ILIKE :q) AND id<>:id ORDER BY username NULLS LAST LIMIT 30");$st->execute(['q'=>'%'.$q.'%','id'=>$u['id']]);return $this->ok(['users'=>$st->fetchAll()]);}
 public function chatCreate(Request $r):Response{$u=$this->user($r);$b=$r->json();$type=(string)($b['type']??'private');if(!in_array($type,['private','group','channel'],true))return $this->ok(['error'=>'invalid_type'],422);$p=Database::pdo();$p->beginTransaction();$p->prepare('INSERT INTO chats(type,title,created_by) VALUES(:t,:title,:u) RETURNING id')->execute(['t'=>$type,'title'=>$b['title']??null,'u'=>$u['id']]);$id=(int)$p->lastInsertId();if(!$id){$id=(int)$p->query('SELECT currval(pg_get_serial_sequence(\'chats\',\'id\'))')->fetchColumn();}$p->prepare('INSERT INTO chat_members(chat_id,user_id,role) VALUES(:c,:u,:r) ON CONFLICT DO NOTHING')->execute(['c'=>$id,'u'=>$u['id'],'r'=>'owner']);if($type==='group')$p->prepare('INSERT INTO groups(chat_id,topics_enabled,description) VALUES(:c,:t,:d)')->execute(['c'=>$id,'t'=>(bool)($b['topics_enabled']??false),'d'=>$b['description']??null]);if($type==='channel')$p->prepare('INSERT INTO channels(chat_id,is_public,username,description) VALUES(:c,:p,:n,:d)')->execute(['c'=>$id,'p'=>(bool)($b['public']??false),'n'=>$b['username']??null,'d'=>$b['description']??null]);$p->commit();return $this->ok(['chat_id'=>$id],201);}
 public function chats(Request $r):Response{$u=$this->user($r);$st=Database::pdo()->prepare("SELECT c.*,cm.role FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=:u ORDER BY c.created_at DESC");$st->execute(['u'=>$u['id']]);return $this->ok(['chats'=>$st->fetchAll()]);}
 public function membersAdd(Request $r):Response{$u=$this->user($r);$b=$r->json();$c=(int)($b['chat_id']??0);$target=(int)($b['user_id']??0);$p=Database::pdo();$st=$p->prepare("SELECT role FROM chat_members WHERE chat_id=:c AND user_id=:u");$st->execute(['c'=>$c,'u'=>$u['id']]);$role=$st->fetchColumn();if(!in_array($role,['owner','admin','moderator'],true))return $this->ok(['error'=>'forbidden'],403);$p->prepare('INSERT INTO chat_members(chat_id,user_id,role) VALUES(:c,:u,\'member\') ON CONFLICT DO NOTHING')->execute(['c'=>$c,'u'=>$target]);return $this->ok(['ok'=>true]);}
 public function messageSend(Request $r):Response{$u=$this->user($r);$b=$r->json();$c=(int)($b['chat_id']??0);$body=(string)($b['body']??'');if($body===''||strlen($body)>20000)return $this->ok(['error'=>'invalid_body'],422);$p=Database::pdo();$st=$p->prepare('SELECT 1 FROM chat_members WHERE chat_id=:c AND user_id=:u');$st->execute(['c'=>$c,'u'=>$u['id']]);if(!$st->fetchColumn())return $this->ok(['error'=>'forbidden'],403);$p->prepare('INSERT INTO messages(chat_id,sender_id,body,reply_to_id) VALUES(:c,:u,:b,:r)')->execute(['c'=>$c,'u'=>$u['id'],'b'=>$body,'r'=>$b['reply_to_id']??null]);$id=(int)$p->query('SELECT currval(pg_get_serial_sequence(\'messages\',\'id\'))')->fetchColumn();$p->prepare('INSERT INTO audit_logs(user_id,action,metadata) VALUES(:u,\'message.send\',:m)')->execute(['u'=>$u['id'],'m'=>json_encode(['chat_id'=>$c,'message_id'=>$id],JSON_UNESCAPED_UNICODE)]);return $this->ok(['message_id'=>$id],201);}
 public function messages(Request $r):Response{$u=$this->user($r);$b=$r->json();$c=(int)($b['chat_id']??0);$limit=min(100,max(1,(int)($b['limit']??50)));$p=Database::pdo();$st=$p->prepare('SELECT 1 FROM chat_members WHERE chat_id=:c AND user_id=:u');$st->execute(['c'=>$c,'u'=>$u['id']]);if(!$st->fetchColumn())return $this->ok(['error'=>'forbidden'],403);$st=$p->prepare('SELECT m.id,m.chat_id,m.sender_id,m.body,m.reply_to_id,m.edited_at,m.deleted_at,m.created_at,u.username,u.display_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.chat_id=:c ORDER BY m.created_at DESC LIMIT '.$limit);$st->execute(['c'=>$c]);return $this->ok(['messages'=>array_reverse($st->fetchAll())]);}
 public function messageEdit(Request $r):Response{$u=$this->user($r);$b=$r->json();$p=Database::pdo();$st=$p->prepare('UPDATE messages SET body=:b,edited_at=NOW() WHERE id=:m AND sender_id=:u AND deleted_at IS NULL');$st->execute(['b'=>(string)$b['body'],'m'=>(int)$b['message_id'],'u'=>$u['id']]);return $this->ok(['ok'=>$st->rowCount()===1]);}
 public function messageDelete(Request $r):Response{$u=$this->user($r);$b=$r->json();$st=Database::pdo()->prepare('UPDATE messages SET deleted_at=NOW(),body=NULL WHERE id=:m AND sender_id=:u AND deleted_at IS NULL');$st->execute(['m'=>(int)$b['message_id'],'u'=>$u['id']]);return $this->ok(['ok'=>$st->rowCount()===1]);}
 public function reaction(Request $r):Response{$u=$this->user($r);$b=$r->json();$p=Database::pdo();$p->prepare('INSERT INTO message_reactions(message_id,user_id,emoji) VALUES(:m,:u,:e) ON CONFLICT DO NOTHING')->execute(['m'=>(int)$b['message_id'],'u'=>$u['id'],'e'=>(string)$b['emoji']]);return $this->ok(['ok'=>true]);}
 public function settings(Request $r):Response{$u=$this->user($r);$p=Database::pdo();if($r->method()==='GET'){$s=$p->prepare('SELECT settings FROM user_settings WHERE user_id=:u');$s->execute(['u'=>$u['id']]);return $this->ok(['settings'=>$s->fetchColumn()?:[]]);}$settings=$r->json()['settings']??[];$p->prepare("INSERT INTO user_settings(user_id,settings) VALUES(:u,:s) ON CONFLICT(user_id) DO UPDATE SET settings=EXCLUDED.settings")->execute(['u'=>$u['id'],'s'=>json_encode($settings,JSON_UNESCAPED_UNICODE)]);return $this->ok(['ok'=>true]);}
 public function callToken(Request $r):Response{$u=$this->user($r);$secret=(string)($_ENV['CALL_SHARED_SECRET']??getenv('CALL_SHARED_SECRET')??'');if(strlen($secret)<32)return $this->ok(['error'=>'calls_not_configured'],503);$head=base64_encode(json_encode(['alg'=>'HS256','typ'=>'PCT']));$payload=base64_encode(json_encode(['uid'=>(int)$u['id'],'sid'=>$u['session_id'],'exp'=>time()+300,'jti'=>Security::token(16)]));$sig=hash_hmac('sha256',$head.'.'.$payload,$secret,true);return $this->ok(['token'=>$head.'.'.$payload.'.'.rtrim(strtr(base64_encode($sig),'+/','-_'),'=')]);}
}