<?php
declare(strict_types=1);
namespace PlusChat;
use PlusChat\Auth\Auth;use PlusChat\Http\Request;use PlusChat\Http\Response;
final class FeatureController{
 private function u(Request $r):array{$u=Auth::user($r);if(!$u)throw new \RuntimeException('unauthorized');return $u;}
 private function j(mixed $x,int $s=200):Response{return Response::json($x,$s);}
 private function member(int $c,int $u):bool{$s=Database::pdo()->prepare('SELECT 1 FROM chat_members WHERE chat_id=:c AND user_id=:u');$s->execute(['c'=>$c,'u'=>$u]);return(bool)$s->fetchColumn();}
 public function topics(Request $r):Response{$u=$this->u($r);$b=$r->json();$c=(int)($b['chat_id']??$r->query['chat_id']??0);if(!$this->member($c,$u['id']))return $this->j(['error'=>'forbidden'],403);$p=Database::pdo();if($r->method()==='GET'){$s=$p->prepare('SELECT * FROM topics WHERE chat_id=:c ORDER BY archived,created_at');$s->execute(['c'=>$c]);return $this->j(['topics'=>$s->fetchAll()]);}$name=trim((string)($b['name']??''));if($name==='')return $this->j(['error'=>'invalid_name'],422);$p->prepare('INSERT INTO topics(chat_id,name,icon) VALUES(:c,:n,:i)')->execute(['c'=>$c,'n'=>$name,'i'=>$b['icon']??null]);return $this->j(['ok'=>true],201);}
 public function topicUpdate(Request $r):Response{$u=$this->u($r);$b=$r->json();$p=Database::pdo();$s=$p->prepare('SELECT chat_id FROM topics WHERE id=:t');$s->execute(['t'=>(int)$b['topic_id']]);$c=$s->fetchColumn();if(!$c||!$this->member((int)$c,$u['id']))return $this->j(['error'=>'forbidden'],403);$p->prepare('UPDATE topics SET name=COALESCE(:n,name),icon=COALESCE(:i,icon),archived=COALESCE(:a,archived) WHERE id=:t')->execute(['n'=>$b['name']??null,'i'=>$b['icon']??null,'a'=>$b['archived']??null,'t'=>(int)$b['topic_id']]);return $this->j(['ok'=>true]);}
 public function contacts(Request $r):Response{$u=$this->u($r);$p=Database::pdo();if($r->method()==='GET'){$s=$p->prepare('SELECT u.id,u.username,u.display_name,u.avatar_file_id,c.alias FROM contacts c JOIN users u ON u.id=c.contact_id WHERE c.owner_id=:u ORDER BY c.created_at DESC');$s->execute(['u'=>$u['id']]);return $this->j(['contacts'=>$s->fetchAll()]);}$b=$r->json();$id=(int)($b['user_id']??0);if($id<1||$id===$u['id'])return $this->j(['error'=>'invalid_user'],422);$p->prepare('INSERT INTO contacts(owner_id,contact_id,alias) VALUES(:o,:c,:a) ON CONFLICT(owner_id,contact_id) DO UPDATE SET alias=EXCLUDED.alias')->execute(['o'=>$u['id'],'c'=>$id,'a'=>$b['alias']??null]);return $this->j(['ok'=>true]);}
 public function block(Request $r):Response{$u=$this->u($r);$b=$r->json();$p=Database::pdo();$p->prepare('INSERT INTO blocks(owner_id,blocked_id) VALUES(:o,:b) ON CONFLICT DO NOTHING')->execute(['o'=>$u['id'],'b'=>(int)$b['user_id']]);return $this->j(['ok'=>true]);}
 public function report(Request $r):Response{$u=$this->u($r);$b=$r->json();Database::pdo()->prepare('INSERT INTO reports(reporter_id,target_user_id,chat_id,message_id,reason,details) VALUES(:r,:u,:c,:m,:reason,:d)')->execute(['r'=>$u['id'],'u'=>$b['target_user_id']??null,'c'=>$b['chat_id']??null,'m'=>$b['message_id']??null,'reason'=>(string)($b['reason']??'other'),'d'=>$b['details']??null]);return $this->j(['ok'=>true],201);}
 public function notifications(Request $r):Response{$u=$this->u($r);$p=Database::pdo();if($r->method()==='POST'){$b=$r->json();$p->prepare('UPDATE notifications SET read_at=NOW() WHERE user_id=:u AND id=:i')->execute(['u'=>$u['id'],'i'=>(int)$b['id']]);return $this->j(['ok'=>true]);}$s=$p->prepare('SELECT * FROM notifications WHERE user_id=:u ORDER BY created_at DESC LIMIT 100');$s->execute(['u'=>$u['id']]);return $this->j(['notifications'=>$s->fetchAll()]);}
 public function search(Request $r):Response{$u=$this->u($r);$q=trim((string)($r->query['q']??$r->json()['q']??''));if(strlen($q)<2)return $this->j(['messages'=>[]]);$s=Database::pdo()->prepare("SELECT m.id,m.chat_id,m.sender_id,m.body,m.created_at FROM messages m JOIN chat_members cm ON cm.chat_id=m.chat_id AND cm.user_id=:u WHERE m.deleted_at IS NULL AND m.body ILIKE :q ORDER BY m.created_at DESC LIMIT 50");$s->execute(['u'=>$u['id'],'q'=>'%'.$q.'%']);return $this->j(['messages'=>$s->fetchAll()]);}
 public function chatSetting(Request $r):Response{$u=$this->u($r);$b=$r->json();$c=(int)($b['chat_id']??$r->query['chat_id']??0);if(!$this->member($c,$u['id']))return $this->j(['error'=>'forbidden'],403);$p=Database::pdo();if($r->method()==='GET'){$s=$p->prepare('SELECT * FROM chat_settings WHERE chat_id=:c AND user_id=:u');$s->execute(['c'=>$c,'u'=>$u['id']]);return $this->j(['settings'=>$s->fetch()?:[]]);}$p->prepare("INSERT INTO chat_settings(chat_id,user_id,muted,archived,disappearing_seconds,topic_notifications) VALUES(:c,:u,:m,:a,:d,:t) ON CONFLICT(chat_id,user_id) DO UPDATE SET muted=EXCLUDED.muted,archived=EXCLUDED.archived,disappearing_seconds=EXCLUDED.disappearing_seconds,topic_notifications=EXCLUDED.topic_notifications")->execute(['c'=>$c,'u'=>$u['id'],'m'=>(bool)($b['muted']??false),'a'=>(bool)($b['archived']??false),'d'=>$b['disappearing_seconds']??null,'t'=>(bool)($b['topic_notifications']??true)]);return $this->j(['ok'=>true]);}
 public function pollCreate(Request $r):Response{$u=$this->u($r);$b=$r->json();$c=(int)$b['chat_id'];if(!$this->member($c,$u['id']))return $this->j(['error'=>'forbidden'],403);$opts=$b['options']??[];if(!is_array($opts)||count($opts)<2||count($opts)>20)return $this->j(['error'=>'invalid_options'],422);Database::pdo()->prepare('INSERT INTO polls(chat_id,creator_id,question,options,anonymous) VALUES(:c,:u,:q,:o,:a)')->execute(['c'=>$c,'u'=>$u['id'],'q'=>(string)$b['question'],'o'=>json_encode(array_values($opts),JSON_UNESCAPED_UNICODE),'a'=>(bool)($b['anonymous']??false)]);return $this->j(['ok'=>true],201);}
 public function pollVote(Request $r):Response{$u=$this->u($r);$b=$r->json();$p=Database::pdo();$s=$p->prepare('SELECT options FROM polls WHERE id=:p');$s->execute(['p'=>(int)$b['poll_id']]);$o=$s->fetchColumn();if(!$o)return $this->j(['error'=>'not_found'],404);$opts=json_decode($o,true);$i=(int)$b['option_index'];if(!isset($opts[$i]))return $this->j(['error'=>'invalid_option'],422);$p->prepare('INSERT INTO poll_votes(poll_id,user_id,option_index) VALUES(:p,:u,:i) ON CONFLICT(poll_id,user_id) DO UPDATE SET option_index=EXCLUDED.option_index')->execute(['p'=>(int)$b['poll_id'],'u'=>$u['id'],'i'=>$i]);return $this->j(['ok'=>true]);}
}
