<?php
declare(strict_types=1);
namespace PlusChat;
use PlusChat\Auth\Auth;use PlusChat\Http\Request;use PlusChat\Http\Response;
final class FileController{
 private function key():string{$v=(string)(getenv('FILE_ENCRYPTION_KEY')?:'');$d=base64_decode($v,true);if($d!==false&&strlen($d)===SODIUM_CRYPTO_SECRETBOX_KEYBYTES)return $d;if(strlen($v)===SODIUM_CRYPTO_SECRETBOX_KEYBYTES)return $v;throw new \RuntimeException('storage_not_configured');}
 private function path(string $id):string{if(!preg_match('/^[a-f0-9]{32}$/',$id))throw new \RuntimeException('not_found');$root=rtrim((string)(getenv('PRIVATE_STORAGE_PATH')?:dirname(__DIR__).'/storage/files'),'/');return $root.'/'.$id.'.bin';}
 public function upload(Request $r):Response{$u=Auth::require($r);$f=$r->files['file']??null;if(!is_array($f)||($f['error']??1)!==UPLOAD_ERR_OK)return Response::json(['error'=>'upload_failed'],400);$max=(int)(getenv('MAX_UPLOAD_BYTES')?:52428800);if((int)$f['size']<1||(int)$f['size']>$max)return Response::json(['error'=>'file_size'],413);$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name'])?:'';$allowed=['image/jpeg','image/png','image/webp','image/gif','video/mp4','audio/mpeg','audio/ogg','audio/webm','application/pdf','text/plain','application/zip'];if(!in_array($mime,$allowed,true))return Response::json(['error'=>'mime_not_allowed'],415);$raw=file_get_contents($f['tmp_name']);$key=$this->key();$nonce=random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);$cipher=$nonce.sodium_crypto_secretbox($raw,$nonce,$key);$id=bin2hex(random_bytes(16));$root=rtrim((string)(getenv('PRIVATE_STORAGE_PATH')?:dirname(__DIR__).'/storage/files'),'/');if(!is_dir($root)&&!mkdir($root,0700,true)&&!is_dir($root))throw new \RuntimeException('storage_failed');$path=$root.'/'.$id.'.bin';if(file_put_contents($path,$cipher,LOCK_EX)===false)throw new \RuntimeException('storage_failed');try{Database::pdo()->prepare('INSERT INTO files(id,owner_id,original_name,mime_type,size_bytes,sha256,storage_path,encrypted) VALUES(?,?,?,?,?,?,?,TRUE)')->execute([$id,$u['id'],basename((string)$f['name']),$mime,(int)$f['size'],hash('sha256',$raw,true),$path]);}catch(\Throwable $e){@unlink($path);throw $e;}return Response::json(['file_id'=>$id,'size'=>(int)$f['size'],'mime'=>$mime],201);}
 public function download(Request $r):never{$u=Auth::require($r);$id=(string)($r->query['id']??'');$s=Database::pdo()->prepare('SELECT * FROM files WHERE id=?');$s->execute([$id]);$f=$s->fetch();if(!$f)Response::json(['error'=>'not_found'],404)->send();$ok=((int)$f['owner_id']===(int)$u['id']);if(!$ok){$q=Database::pdo()->prepare('SELECT 1 FROM chat_members cm JOIN messages m ON m.chat_id=cm.chat_id WHERE cm.user_id=? AND m.body LIKE ? LIMIT 1');$q->execute([$u['id'],'%'.$id.'%']);$ok=(bool)$q->fetchColumn();}if(!$ok)Response::json(['error'=>'forbidden'],403)->send();$path=$this->path($id);if(!is_file($path))Response::json(['error'=>'not_found'],404)->send();$cipher=file_get_contents($path);$nonce=substr($cipher,0,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);$plain=sodium_crypto_secretbox_open(substr($cipher,SODIUM_CRYPTO_SECRETBOX_NONCEBYTES),$nonce,$this->key());if($plain===false)Response::json(['error'=>'decrypt_failed'],500)->send();header('Content-Type: '.$f['mime_type']);header('Content-Length: '.strlen($plain));header('Content-Disposition: inline; filename="'.addcslashes($f['original_name'],'"\\').'"');header('X-Content-Type-Options: nosniff');echo $plain;exit;}
}
